<?php

namespace ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function findAllAlphabetically(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT p FROM ContactBundle:Person p
            ORDER BY p.lastname ASC');
        return $query->getResult();
    }
}
